volumes:
  postgres-volume:
    driver: local

services:
  cieid-postgres:
    image: postgres:18.4 # Latest supported version -> https://www.keycloak.org/server/supported-configurations
    container_name: "cieid-postgres"
    networks:
      - cieid-local-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${CIEID_DB_SCHEMA}
      POSTGRES_USER: ${CIEID_DB_USR}
      POSTGRES_PASSWORD: ${CIEID_DB_PWD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${CIEID_DB_USR}", "-d", "${CIEID_DB_SCHEMA}"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-volume:/var/lib/postgresql/18/docker
